version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /var/www/backend:/var/www/backend
      - /var/www/frontend:/var/www/frontend
      - /var/www/Web/blossoming-blade:/var/www/Web/blossoming-blade
    user: root